proxy:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/nginx_config:/etc/nginx
    - ${NFS_HOST}${NFS_FOLDER}/nginx_releasenote:/usr/share/nginx/html

ldap:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/ldap_db:/var/lib/ldap
    - ${NFS_HOST}${NFS_FOLDER}/ldap_static:/etc/ldap

gerrit-mysql:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/gerrit_mysql_data:/var/lib/mysql

gerrit:
  user: root
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/git_repos:/var/git/repos
    - ${NFS_HOST}${NFS_FOLDER}/gerrit_review_site:/var/gerrit/review_site

sensu-api:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/sensu_api_conf:/etc/sensu/conf.d

sensu-server:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/sensu_server_conf:/etc/sensu/conf.d

sensu-client:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/sensu_client_conf:/etc/sensu/conf.d

sensu-rabbitmq:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/sensu_rabbitmq_data:/var/lib/rabbitmq

sensu-redis:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/sensu_redis_data:/data

sonar-mysql:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/sonar_mysql_data:/var/lib/mysql

sonar:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/sonar_data:/opt/sonarqube/data
    - ${NFS_HOST}${NFS_FOLDER}/sonar_extensions:/opt/sonarqube/extensions
    - ${NFS_HOST}${NFS_FOLDER}/sonar_logs:/opt/sonarqube/logs

jenkins:
  user: root
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/jenkins_home:/var/jenkins_home

selenium-node-chrome:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/selenium_config:/var/selenium-config

selenium-node-firefox:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/selenium_config:/var/selenium-config

nexus:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/nexus_sonatype_work:/sonatype-work

registry:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}${NFS_FOLDER}/registry_certs:/certs
    - ${NFS_HOST}${NFS_FOLDER}/registry_data:/data
